[ENDPOINT]
hostname = pacs.site-b
port = 4242
ae_title = TARGET_PACS
# This endpoint specifically might not want Ultrasound images
blacklist = 1.2.840.10008.5.1.4.1.1.6.1
[SCHEDULE]
scheduled = m10 < 2
; Cyclic format for testing purposes:
; m10 < 5  -> Sends during the first 5 minutes of every 10-minute block
; Revert to this for production/live environment
# scheduled = 18:00-22:00, 22:30-6:00 
[DEBUG]
logname = Endpoint-remote
# DEBUG , INFO , WARNING , ERROR , CRITICAL
loglevel = INFO
