[DICOM]
ae_title = ROUTER_AET
# List of SOP Class UIDs to reject, separated by comma
blacklist = 1.2.840.10008.5.1.4.1.1.2
[DEBUG]
logname = Router
# DEBUG , INFO , WARNING , ERROR , CRITICAL
loglevel = INFO
