[ENDPOINT]
hostname = pacs.site-a
port = 4242
ae_title = TARGET_PACS
# This endpoint specifically might not want Ultrasound images
blacklist = 1.2.840.10008.5.1.4.1.1.6.1
[DEBUG]
logname = Endpoint-local
# DEBUG , INFO , WARNING , ERROR , CRITICAL
loglevel = INFO
